services:
  searxng:
    image: searxng/searxng:latest
    container_name: nemo_searxng
    restart: unless-stopped
    ports:
      - "8888:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8888/
      - INSTANCE_NAME=nemo_searxng
